// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATbNxVF2-jf5-RJma-XuaXOhtrE2HDkAA',
    appId: '1:149651353441:web:96f55297a9f28538615f20',
    messagingSenderId: '149651353441',
    projectId: 'c2cnocevents',
    authDomain: 'c2cnocevents.firebaseapp.com',
    storageBucket: 'c2cnocevents.firebasestorage.app',
    measurementId: 'G-HNQ079BZKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbS_k9WpOR-gnxt7PbuS1K8l3OTGeKkCk',
    appId: '1:149651353441:android:18205ec8d6245021615f20',
    messagingSenderId: '149651353441',
    projectId: 'c2cnocevents',
    storageBucket: 'c2cnocevents.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKu9Rap1LBVfaE9jlDzC3bOsj3b7OR9o0',
    appId: '1:149651353441:ios:bb4ebcce1f994048615f20',
    messagingSenderId: '149651353441',
    projectId: 'c2cnocevents',
    storageBucket: 'c2cnocevents.firebasestorage.app',
    iosBundleId: 'com.teamupnc.app',
  );
}
